# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/kgopal/Desktop/Prarthit/lab3/viv/project_4/project_4.cache/wt [current_project]
set_property parent.project_path /home/kgopal/Desktop/Prarthit/lab3/viv/project_4/project_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/kgopal/Desktop/Prarthit/lab3/viv/project_4/project_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/kgopal/Desktop/Prarthit/lab3/viv/project_4/project_4.srcs/sources_1/imports/lab3_reg_file/lab3_reg_file.vhf
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/kgopal/Desktop/Prarthit/lab3/viv/project_4/project_4.srcs/constrs_1/imports/Downloads/lab3_reg_file.xdc
set_property used_in_implementation false [get_files /home/kgopal/Desktop/Prarthit/lab3/viv/project_4/project_4.srcs/constrs_1/imports/Downloads/lab3_reg_file.xdc]


synth_design -top lab3_reg_file -part xc7a35tcpg236-1


write_checkpoint -force -noxdef lab3_reg_file.dcp

catch { report_utilization -file lab3_reg_file_utilization_synth.rpt -pb lab3_reg_file_utilization_synth.pb }
